version: '3'

services: 
 php: 
  build: ./.docker/php
  volumes: 
   - ./:/var/www
 nginx:
  build: ./.docker/nginx
  restart: always
  ports: 
   - "8080:80"
  volumes: 
   - ./:/var/www
  depends_on: 
   - php